# Generated by Django 5.2.9 on 2026-07-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_scheduleentry_online_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('lesson_view', 'طالب شاهد الدرس'), ('test_attempt', 'طالب حل الاختبار'), ('lesson_publish', 'درس جديد منشور'), ('test_publish', 'اختبار جديد منشور'), ('schedule_update', 'تحديث جدول المهام'), ('grade_update', 'تحديث درجة'), ('test_modified', 'تعديل في الاختبار'), ('parent_grade', 'رصد درجة الطالب'), ('parent_note', 'ملاحظة من المعلم'), ('parent_attention', 'تنبيه تشتت الانتباه'), ('parent_lesson', 'درس جديد للطالب'), ('parent_test', 'اختبار جديد للطالب'), ('parent_result', 'نتيجة اختبار الطالب')], db_column='NotifType', max_length=20),
        ),
    ]
