# Generated by Django 5.2.9 on 2026-06-04 20:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0043_alter_studentteacherassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gemini_api_key',
            field=models.CharField(blank=True, db_column='Student_Gemini_API_Key', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='daily_gemini_limit',
            field=models.IntegerField(db_column='DailyGeminiLimit', default=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gemini_attempts_today',
            field=models.IntegerField(db_column='GeminiAttemptsToday', default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gemini_last_reset_date',
            field=models.DateField(db_column='GeminiLastResetDate', default=django.utils.timezone.now),
        ),
    ]
