# Generated by Django 5.2.9 on 2026-06-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0044_student_gemini_api_key_teacher_daily_gemini_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='daily_gemini_limit',
            field=models.IntegerField(db_column='DailyGeminiLimit', default=50),
        ),
    ]
