# Generated by Django 5.2.9 on 2026-06-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0045_alter_teacher_daily_gemini_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='daily_gemini_limit',
            field=models.IntegerField(db_column='DailyGeminiLimit', default=20),
        ),
    ]
