# Generated by Django 5.2.9 on 2026-06-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0046_alter_teacher_daily_gemini_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_code',
            field=models.CharField(blank=True, db_column='EmailVerificationCode', help_text='رمز التحقق من الإيميل (8 خانات)', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, db_column='EmailVerificationSentAt', help_text='وقت إرسال رمز التحقق', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(db_column='IsEmailVerified', default=False, help_text='هل تم التحقق من الإيميل'),
        ),
    ]
