# Generated by Django 5.2.9 on 2026-07-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0049_lessoncontent_video_published_vrlesson_vr_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vrlesson',
            name='vr_url',
            field=models.URLField(blank=True, db_column='VR_URL', help_text='ط±ط§ط¨ط· ظ…ظ†طµط© ط§ظ„ظˆط§ظ‚ط¹ ط§ظ„ط§ظپطھط±ط§ط¶ظٹ ط§ظ„ظ…طµظ…ظ… ظ…ظ† ظ‚ط¨ظ„ ط§ظ„ظ…ط¹ظ„ظ…', max_length=1000, null=True),
        ),
    ]
