# Generated by Django 5.2.9 on 2026-07-04 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0050_lessoncontent_video_published_alter_vrlesson_vr_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentVRInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_downloaded_attachment', models.BooleanField(db_column='HasDownloadedAttachment', default=False, help_text='هل قام الطالب بتحميل المرفق؟')),
                ('has_explored_vr', models.BooleanField(db_column='HasExploredVR', default=False, help_text='هل قام الطالب بالضغط على زر استكشاف VR؟')),
                ('download_timestamp', models.DateTimeField(blank=True, db_column='DownloadTimestamp', help_text='وقت تحميل المرفق', null=True)),
                ('explore_timestamp', models.DateTimeField(blank=True, db_column='ExploreTimestamp', help_text='وقت استكشاف VR', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('student', models.ForeignKey(db_column='StudentID', on_delete=django.db.models.deletion.CASCADE, related_name='vr_interactions', to='learning.student')),
                ('vr_lesson', models.ForeignKey(db_column='VRLessonID', on_delete=django.db.models.deletion.CASCADE, related_name='student_interactions', to='learning.vrlesson')),
            ],
            options={
                'db_table': 'StudentVRInteraction',
                'managed': True,
                'indexes': [models.Index(fields=['vr_lesson', 'student'], name='idx_vr_interaction'), models.Index(fields=['student'], name='idx_vr_student')],
                'unique_together': {('vr_lesson', 'student')},
            },
        ),
    ]
