# Generated by Django 5.1.6 on 2026-07-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0051_lessoncontent_video_published_studentvrinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncontent',
            name='video_published',
            field=models.BooleanField(db_column='video_published', default=False),
        ),
    ]
