# Generated by Django 5.1.6 on 2026-07-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0054_migrate_old_scores'),
    ]

    operations = [
        # جعل الحقل nullable أولاً قبل الحذف
        migrations.AlterField(
            model_name='testattempt',
            name='score',
            field=models.IntegerField(db_column='Score', null=True, blank=True),
        ),
        # ثم حذفه
        migrations.RemoveField(
            model_name='testattempt',
            name='score',
        ),
    ]
