# Generated by Django 5.2.9 on 2026-07-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0056_lessoncontent_video_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncontent',
            name='video_published',
            field=models.BooleanField(db_column='video_published', default=False),
        ),
    ]
