# Generated by Django 5.2.9 on 2026-07-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0057_lessoncontent_video_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_version',
            field=models.IntegerField(db_column='TestVersion', default=1, help_text='نسخة الاختبار الحالية'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='test_version',
            field=models.IntegerField(db_column='TestVersion', default=1, help_text='نسخة الاختبار عند المحاولة'),
        ),
    ]
