# Generated by Django 5.2.9 on 2026-07-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0058_test_test_version_testattempt_test_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_letter',
            field=models.CharField(choices=[('A', 'أ'), ('B', 'ب'), ('C', 'ج'), ('D', 'د')], db_column='CorrectLetter', default='A', help_text='رمز الإجابة الصحيحة (أ ب ج د)', max_length=1),
        ),
    ]
