# Generated by Django 5.1.6 on 2026-07-28 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0059_question_correct_letter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_letter',
        ),
    ]
